/*! ued-todo-v1.0.0 2015-11-05 */
/* //

www.17173.com/ */

/* Copyright (c) 2013 17173.com */

/* Licensed same as jquery - MIT License */
/* //

www.opensource.org/licenses/mit-license.php */

/* email: changjianwang@cyou-inc.com */
adv.AdBase.extend("AdGlobalMoneyQiYu",{_addCSS:function(a){var b=document.createElement("style"),c=document.head||document.getElementsByTagName("head")[0];if(b.type="text/css",b.styleSheet){var d=function(){try{b.styleSheet.cssText=a}catch(c){}};b.styleSheet.disabled?setTimeout(d,10):d()}else{var e=document.createTextNode(a);b.appendChild(e)}c.appendChild(b)},_getWindowWidth:function(){return Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)},_on:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)},_positionFixed:function(a,b){window.XMLHttpRequest||(a.style.position="absolute",a.style.top=document.documentElement.scrollTop+b+"px",window.attachEvent("onscroll",function(){a.style.top=document.documentElement.scrollTop+b+"px"}))},_setIe6Img:function(a,b){var c=this;a&&adv.$("."+c.options.advid).find(a).css({cursor:"pointer",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=noscale, src='"+b+"')",background:"none"})},init:function(a){this.base(a),this.options.type&&(~location.href.indexOf("nomoney=true")||window.disableAdGlobalMoneyQiYu1||window.noToprightFloatAd||(window.youqiyuguanggao=!0,this._addCSS(".ad-zhanneituiguang{display: none;}"),this.emit(adv.ENUM.EVENTS.inited)))},setup:function(){this.base();var a=this.options,b="",c="",d="position: absolute;bottom: 0;left: 0;width: 13px;height: 13px;background: #fff;color: #000;font-weight: bold;text-decoration: none;padding:0;margin:0;line-height:19px;";this.closeEl=adv.$('<a class="close" href="javascript://" style="'+d+'"><img src="//

ue1.17173.itc.cn/a/www/index/2013/images/close.gif" style="width:13px;height:13px"/></a>'),this.html=adv.$('<div id="moneyQiYu" class="money-qiyu '+this.options.advid+'" style="position: fixed; /*width:180px;height:320px;*/top: 80px;z-index:1010;"></div>'),this.bigWrapEl=adv.$('<div class="big-box"></div>'),this.smallWrapEl=adv.$('<div class="small-box" style="display:none;position: fixed;width:30px;height:35px;top: 80px;z-index:1010;"></div>'),this.bigWrapEl.append(this.closeEl),a.height=a.height||"auto",a.width=a.width||"auto",b=a.bigImg.indexOf(".swf")>=0?adv.flash.embed({source:a.bigImg,width:a.width,height:a.height,params:{flashvars:a.link}}):'<a class="bigImg" href="'+a.link+'" target="_blank" style="width:'+a.width+"px; height:"+a.height+"px; background:url("+a.bigImg+'); background-repeat:no-repeat; display:block;"></a>',c=a.smallImg.indexOf(".swf")>=0?adv.flash.embed({source:a.smallImg,width:a.sWidth,height:a.sHeight,params:{flashvars:a.link}}):'<img style="cursor: pointer;" src="'+a.smallImg+'" border="0" height="'+a.sHeight+'" width="'+a.sWidth+'">',this.bigWrapEl.append(b),this.smallWrapEl.append(c),this.html.append(this.bigWrapEl),this.html.append(this.smallWrapEl),this.emit(adv.ENUM.EVENTS.setuped)},_getLeft:function(){var a=this,b=this.options,c=a._getWindowWidth();return window.contentWidthAdGlobalMoneyQiYu1&&(b.contentWidth=window.contentWidthAdGlobalMoneyQiYu1),b.contentWidth+Math.floor((c-b.contentWidth)/2)+10},play:function(){var a=this,b=this.options,c=a.html;this.base(),left=a._getLeft(),c.css({left:left}),adv.$("body").append(c);var d=!!window.ActiveXObject&&!window.XMLHttpRequest;d?(a._positionFixed(document.getElementById("moneyQiYu"),b.top),a._setIe6Img(".bigImg",b.bigImg)):c.css({position:"fixed",top:b.top});var e=adv.$("."+a.options.advid),f=e.find(".small-box"),g=e.find(".big-box");e.find(".close").on("click",function(){g.hide(),f.show()}),f.on("click",function(){g.show(),f.hide()}),a._on(window,"resize",function(){setTimeout(function(){c.css({left:a._getLeft()})},500)}),this.emit(adv.ENUM.EVENTS.played)},stop:function(){this.base(),this.emit(adv.ENUM.EVENTS.stoped)},dispose:function(){}});